# Generated by Django 4.2.13 on 2026-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_no', models.CharField(blank=True, max_length=20, verbose_name='T.C. / Pasaport No')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadın'), ('O', 'Diğer')], max_length=1, verbose_name='Cinsiyet')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('?', 'Bilinmiyor')], default='?', max_length=3, verbose_name='Kan Grubu')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, verbose_name='Acil Kişi Adı')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Acil Kişi Telefonu')),
                ('insurance_info', models.CharField(blank=True, max_length=200, verbose_name='Sigorta Bilgisi')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Meslek')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar / Uyarılar')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSIVE', 'Pasif')], default='ACTIVE', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hasta',
                'verbose_name_plural': 'Hastalar',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, verbose_name='Alerjiler')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Kronik Hastalıklar')),
                ('regular_medicines', models.TextField(blank=True, verbose_name='Sürekli Kullanılan İlaçlar')),
                ('surgeries', models.TextField(blank=True, verbose_name='Geçirilmiş Ameliyatlar')),
                ('family_history', models.TextField(blank=True, verbose_name='Aile Hastalık Geçmişi')),
                ('smoking', models.CharField(blank=True, max_length=50, verbose_name='Sigara')),
                ('alcohol', models.CharField(blank=True, max_length=50, verbose_name='Alkol')),
                ('pregnancy_info', models.CharField(blank=True, max_length=100, verbose_name='Gebelik Bilgisi')),
                ('special_notes', models.TextField(blank=True, verbose_name='Özel Notlar')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Tıbbi Bilgi',
                'verbose_name_plural': 'Tıbbi Bilgiler',
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(max_length=50, verbose_name='Onay Türü')),
                ('approved', models.BooleanField(default=False, verbose_name='Onaylandı')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('consent_text_version', models.CharField(default='1.0', max_length=20, verbose_name='Metin Versiyonu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'KVKK Onay',
                'verbose_name_plural': 'KVKK Onayları',
            },
        ),
    ]
