# Generated by Django 4.2.13 on 2026-04-25 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientconsent',
            options={'ordering': ['-created_at'], 'verbose_name': 'KVKK Onay', 'verbose_name_plural': 'KVKK Onayları'},
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_consents', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden'),
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='consent_type',
            field=models.CharField(choices=[('KVKK', 'KVKK Aydınlatma Metni'), ('COMMUNICATION', 'İletişim İzni'), ('TREATMENT', 'Tedavi Onamı'), ('SURGERY', 'Ameliyat Onamı'), ('PHOTOGRAPHY', 'Fotoğraf / Video İzni'), ('OTHER', 'Diğer')], default='KVKK', max_length=20, verbose_name='Onay Türü'),
        ),
    ]
