# Generated by Django 4.2.13 on 2026-04-25 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Branş Adı')),
            ],
            options={
                'verbose_name': 'Branş',
                'verbose_name_plural': 'Branşlar',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Unvan')),
                ('diploma_no', models.CharField(blank=True, max_length=50, verbose_name='Diploma No')),
                ('color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Takvim Rengi')),
                ('status', models.BooleanField(default=True, verbose_name='Aktif')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.branch', verbose_name='Branş')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Doktor',
                'verbose_name_plural': 'Doktorlar',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_start', models.DateTimeField(verbose_name='Randevu Başlangıcı')),
                ('appointment_end', models.DateTimeField(verbose_name='Randevu Bitişi')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('CONFIRMED', 'Onaylandı'), ('ARRIVED', 'Geldi'), ('IN_EXAM', 'Muayenede'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal Edildi'), ('NO_SHOW', 'Gelmedi'), ('RESCHEDULED', 'Ertelendi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('appointment_type', models.CharField(choices=[('REGULAR', 'Normal Muayene'), ('CONTROL', 'Kontrol'), ('EMERGENCY', 'Acil'), ('ONLINE', 'Online')], default='REGULAR', max_length=20, verbose_name='Tür')),
                ('note', models.TextField(blank=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-appointment_start'],
            },
        ),
    ]
