# Generated by Django 4.2.13 on 2026-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('examinations', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hizmet Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('status', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim')),
                ('payment_type', models.CharField(choices=[('CASH', 'Nakit'), ('CARD', 'Kredi / Banka Kartı'), ('TRANSFER', 'Havale / EFT'), ('INSURANCE', 'Sigorta'), ('OTHER', 'Diğer')], default='CASH', max_length=20, verbose_name='Ödeme Türü')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('PAID', 'Ödendi'), ('PARTIAL', 'Kısmi Ödeme'), ('REFUNDED', 'İade Edildi'), ('CANCELLED', 'İptal')], default='PENDING', max_length=20, verbose_name='Ödeme Durumu')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='appointments.appointment', verbose_name='Randevu')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='examinations.examination', verbose_name='Muayene')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='patients.patient', verbose_name='Hasta')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.service', verbose_name='Hizmet')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
