# Generated by Django 4.2.13 on 2026-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, verbose_name='Şikayet')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Anamnez / Hikaye')),
                ('findings', models.TextField(blank=True, verbose_name='Fizik Muayene Bulguları')),
                ('pre_diagnosis', models.CharField(blank=True, max_length=300, verbose_name='Ön Tanı')),
                ('diagnosis', models.CharField(blank=True, max_length=300, verbose_name='Kesin Tanı')),
                ('icd10_code', models.CharField(blank=True, max_length=20, verbose_name='ICD-10 Kodu')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Tedavi Planı')),
                ('doctor_note', models.TextField(blank=True, verbose_name='Doktor Notu (İç)')),
                ('result', models.TextField(blank=True, verbose_name='Muayene Sonucu')),
                ('control_date', models.DateField(blank=True, null=True, verbose_name='Kontrol Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Muayene Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination', to='appointments.appointment', verbose_name='Randevu')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='appointments.doctor', verbose_name='Doktor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Muayene',
                'verbose_name_plural': 'Muayeneler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Boy (cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Kilo (kg)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='VKİ')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Ateş (°C)')),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nabız (bpm)')),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sistolik KB')),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Diastolik KB')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Solunum Sayısı')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO2 (%)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Kan Şekeri')),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ağrı Skoru (0-10)')),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='examinations.examination', verbose_name='Muayene')),
            ],
            options={
                'verbose_name': 'Vital Bulgular',
                'verbose_name_plural': 'Vital Bulgular',
            },
        ),
    ]
