# Generated by Django 4.2.13 on 2026-04-25 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examinations', '0002_examinationservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('category', models.CharField(choices=[('GENERAL', 'Genel'), ('ENT', 'KBB'), ('CARDIOLOGY', 'Kardiyoloji'), ('ORTHOPEDICS', 'Ortopedi'), ('PEDIATRICS', 'Pediatri'), ('DERMATOLOGY', 'Dermatoloji'), ('NEUROLOGY', 'Nöroloji'), ('OTHER', 'Diğer')], default='GENERAL', max_length=20, verbose_name='Kategori')),
                ('complaint', models.TextField(blank=True, verbose_name='Şikayet')),
                ('findings', models.TextField(blank=True, verbose_name='Fizik Muayene Bulguları')),
                ('diagnosis', models.CharField(blank=True, max_length=300, verbose_name='Tanı')),
                ('icd10_code', models.CharField(blank=True, max_length=20, verbose_name='ICD-10 Kodu')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Tedavi Planı')),
                ('doctor_note', models.TextField(blank=True, verbose_name='Doktor Notu')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Herkese Açık')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Muayene Şablonu',
                'verbose_name_plural': 'Muayene Şablonları',
                'ordering': ['category', 'name'],
            },
        ),
    ]
