# Generated by Django 4.2.13 on 2026-04-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('examinations', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True, verbose_name='Reçete Tarihi')),
                ('note', models.TextField(blank=True, verbose_name='Reçete Notu')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.doctor', verbose_name='Doktor')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='examinations.examination', verbose_name='Muayene')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='Hasta')),
            ],
            options={
                'verbose_name': 'Reçete',
                'verbose_name_plural': 'Reçeteler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200, verbose_name='İlaç Adı')),
                ('active_ingredient', models.CharField(blank=True, max_length=200, verbose_name='Etken Madde')),
                ('dosage', models.CharField(max_length=100, verbose_name='Doz')),
                ('frequency', models.CharField(max_length=100, verbose_name='Kullanım Sıklığı')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Kullanım Süresi')),
                ('usage_instruction', models.TextField(blank=True, verbose_name='Kullanım Talimatı')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Not')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription', verbose_name='Reçete')),
            ],
            options={
                'verbose_name': 'Reçete Kalemi',
                'verbose_name_plural': 'Reçete Kalemleri',
            },
        ),
    ]
