# Generated by Django 4.2.13 on 2026-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doz'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kullanım Sıklığı'),
        ),
    ]
