# Generated by Django 4.2.13 on 2026-04-25 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('SUCCESS', 'Başarı'), ('APPOINTMENT', 'Randevu'), ('CONTROL', 'Kontrol'), ('PAYMENT', 'Ödeme')], default='INFO', max_length=20, verbose_name='Tür')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Bağlantı')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
