# Generated by Django 4.2.13 on 2026-04-25 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('examinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LAB', 'Laboratuvar'), ('RADIOLOGY', 'Radyoloji'), ('PHOTO', 'Fotoğraf'), ('CONSENT', 'Onam Formu'), ('PRESCRIPTION', 'Reçete'), ('REPORT', 'Rapor'), ('ID_INSURANCE', 'Kimlik / Sigorta'), ('OTHER', 'Diğer')], default='OTHER', max_length=20, verbose_name='Kategori')),
                ('file', models.FileField(upload_to=documents.models.patient_document_path, validators=[documents.models.validate_file_extension, documents.models.validate_file_size], verbose_name='Dosya')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Orijinal Dosya Adı')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Dosya Boyutu (bayt)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('examination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='examinations.examination', verbose_name='Muayene')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='Hasta')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Belge',
                'verbose_name_plural': 'Belgeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
